version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "jest",
    "browser"
  ]
  style_guide = "airbnb"
  dialect = "typescript"

[[transformers]]
name = "prettier"
enabled = true
